ktor {
  deployment {
    host = localhost
    port = 8088
    maxRequestSize = 100MB
  }
  application {
    modules = [app.ApplicationKt.module]
  }
}

jwt {
  issuer = "https://fototovideoai.store"
  domain = "https://fototovideoai.store"
  audience = ["users", "tokens"]
  secret = "MVX1SJBDWY5FOTOTOAI"
  realm = "ktor users"
}

mobile-app-schemes {
  phototovideoai = "com.nla.phototovideoai"
}

google {
  clientId = "465462077450-jvdh7v9pdukjih4nm4qtae5kbsgmd0co.apps.googleusercontent.com"
  clientSecret = "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",
  urlProvider = "https://fototovideoai.store:8087"
}

vk {
  access_token_phototovideoai = "2c18d5cd2c18d5cd2c18d5cd672f26e47222c182c18d5cd45531dd5f18108809bd9a687"
  version = "5.199"
}

postgres {
  url = "jdbc:postgresql://localhost:5432/postgress3"
  user = "postgres"
  password = "J3y%b7Yw:S@CA.geU6"
}

laozhang {
  api_key = "sk-qyMDnIqNS1EiUsMC0b73E6C2Ad01451f93B85bAb569f11Ba"
}

kie {
  api_key = "f9fe6cf21afb924f5755a9eafedc63bb"
}

hedra {
  api_key = "sk_hedra_9gAWsYNNwEQA_ueGtzxEELuOO8B5NVPG17UlhSSFV5MFZzmWtVsiITA0TKEhjgu-"
}

rustore {
  key_id = ""
  folder_key = ""
}

revcat {
  api_key = ""
}

settings {
  start_coins = "100"
  month_sub_coins = "1500"
  year_sub_coins = "13500"
  year_sub_promo_start_coins = "300"
  year_sub_promo_coins = "13500"
  china_main_service = true
  ignore_coins_ios = true
  kie_api_main = false
  is_trial_enabled = true
  prompt1 = """
      Оживи загруженную фотографию
  """
  prompt2 = """
       Сделай плавный переход от фотографиии user-photo1 к фотографии user-photo2
    """
  prompt3 = """
        Сделай видеоаватарку для блога
    """
  prompt4 = """
   """
  prompt5 = """
        Сделай улыбающиегося человека с загруженной фотографии user-photo1
  """
  prompt6 = """
        Сделай репотраж за столом с человеком с загруженной фотографии user-photo1
    """
  prompt7 = """
        Сделай чтобы человек с загруженной фотографии user-photo1 махал рукой в кадре. Не меняй фон.
        Не меняй человека.
    """
  prompt8 = """
        Сделай чтобы человек с загруженной фотографии user-photo1 грозил пальцем в кадр
    """

  prompt13 = """
        Сделай чтобы человек с загруженной фотографии user-photo1 смотрел в кадр и глубоко дышал
    """
  prompt14 = """
        Сделай чтобы человек с загруженной фотографии user-photo1 сидел за столом в бизнес офисе
    """
  prompt15 = """
        Сделай чтобы человек с загруженной фотографии user-photo1 смотрел в камеру и улыбался
    """
  prompt16 = """
        Сделай чтобы человек с загруженной фотографии user-photo1 грозил пальцем в кадр
    """
  prompt17 = """
        Сделай чтобы человек с загруженной фотографии user-photo1 приветственно махал рукой в кадр
    """
}

remote-config {
  price_vk_donut_rub = "499"
  show_onboarding = true
  show_start_paywall = true
  show_more_tokens_button_when_non_sub = true
  show_trial_generation = true
}